### ISSUE TITLE
applySpec tactic is not found

### ISSUE THREAD

**Issue by anton-trunov** [pi8027/mczify#2]
When I compile the project I get the following error:

```
$ make
...
File "./theories/zify.v", line 14, characters 28-37:
Error: The reference applySpec was not found in the current environment.
```

(I updated to Coq to revision `d03529ab8fec0cad5705b5f775e43ef26c0dedcb`)

**Comment by pi8027** [comment]
@anton-trunov Sorry for the belated reply. I have just fixed this in master. Thanks!

**Comment by anton-trunov** [comment]
Thank you so much!
