### ISSUE TITLE
The 8.11 branch does not compile with mathcomp 1.11.0

### ISSUE THREAD

**Issue by MSoegtropIMC** [pi8027/mczify#9]
I updated to mathcomp 1.11.0 which unfortunately had the effect that your zify adoption (thanks for it!) does not compile any more.

The lemmas:
```
Lemma Op_int_min_subproof 
Lemma Op_int_max_subproof
```
fail. The lemma minrP used to prove the first seems to have been deprecated and moved to mathcomp.algebra.ssrnum.mc_1_10.Num.Theory. But even after importing this, case minrP fails and I couldn't figure out why (mathcomp newbie).

**Comment by MSoegtropIMC** [comment]
I found a solution with a more elementary proof, which should work for mathcomp 1.10 and 1.11 (I tested it only on 1.11).
See PR #10.

**Comment by pi8027** [comment]
@MSoegtropIMC FYI, now the `coq-8.11` branch compiles with MathComp 1.11.0 but does not support some (overloaded) operators introduced in MathComp 1.11.0. Since it is painful to maintain several branches that support every combination of Coq (>= 8.11) and MathComp, I think the current status is a realistic solution we can provide now. Yet, when the `zify` tactic and its interface become stable enough (hopefully in Coq 8.13!), I intend to start branching this mczify library based on MathComp versions, which should also support several Coq versions.

**Comment by MSoegtropIMC** [comment]
It is indeed tricky because both lia/zify and mathcomp change quite a bit these days.

Do you have a pointer which operators in mathcomp 1.11 are not supported? Maybe for me it would be a good exercise to learn a bit mathcomp structure and proof style to implement some of this.

Thanks for the great work - having lia/zify is a great help working with mathcomp.

**Comment by pi8027** [comment]
@MSoegtropIMC The interfaces for ordered types (such as `porderType`) and their overloaded operators (le, lt, min, max, meet, join, bottom, top, ...) are new in MathComp 1.11.0. The master branch of mczify supports those operators specialized for bool, nat, int, and their duals.

**Comment by MSoegtropIMC** [comment]
> The interfaces for ordered types (such as porderType, latticeType, and orderType) and their overloaded operators (le, lt, min, max, meet, join, bottom, top, ...) are new in MathComp 1.11.0. 

I see. Did you think about structuring your work differently, say having a separate file for the operators new in mathcomp 1.11 and then having collection files for mathcomp 1.10 and 1.11 which require those component files which are applicable? This might make it easier to maintain your work.

Do you think it would be possible to factor the differences between Coq versions into one file, so that the majority of the content in different Coq version branches would be identical?

**Comment by pi8027** [comment]
@MSoegtropIMC It seems to be another issue, so I answered it in #11.
